In [2]:
#Importamos las  librerías necesarias
import pandas as pd
import numpy as np
from sklearn import  metrics
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

### Paso 1: Leemos el Dataset

In [3]:
dataset_estadisticas_definitivo = pd.read_csv(r"https://raw.githubusercontent.com/PabloLedo97/Datasets-Master-Big-Data/main/DatasetDefinitivo_Pablo_Ledo.csv",sep=";",encoding='latin-1');
dataset_estadisticas_definitivo

Equipo Local/Visitante  Goles_Locales  \
0          Málaga           Local              0   
1         Sevilla       Visitante              0   
2        Atlético           Local              1   
3      Las Palmas       Visitante              0   
4        Espanyol           Local              1   
...           ...             ...            ...   
5315   Villarreal       Visitante              0   
5316  R. Sociedad           Local              1   
5317     Atlético       Visitante              0   
5318      Sevilla           Local              1   
5319     Athletic       Visitante              0   

      Suma_Goles_Locales_Acumulados Media_Goles_Locales  Goles_Visitantes  \
0                                 0                1,37                 0   
1                                 0                   0                 0   
2                                 1                1,74                 0   
3                                 0                   0                 0   
4                                 1                1,16                 0   
...                             ...                 ...               ...   
5315                              0                   0                 2   
5316                             16                0,84                 0   
5317                              0                   0                 2   
5318                             36                1,89                 0   
5319                              0                   0                 0   

      Suma_Goles_Visitantes_Acumulados Media_Goles_Visitantes  Puntos_Locales  \
0                                    0                      0               1   
1                                    0                   0,68               0   
2                                    0                      0               3   
3                                    0                   1,05               0   
4                                    0                      0               3   
...                                ...                    ...             ...   
5315                                20                   1,21               0   
5316                                 0                      0               0   
5317                                32                   1,68               0   
5318                                 0                      0               3   
5319                                14                   0,74               0   

     Media_Puntos_Locales  Puntos_Locales_Acumulados  Puntos_Visitantes  \
0                    1,58                          1                  0   
1                       0                          0                  1   
2                    2,53                          3                  0   
3                       0                          0                  0   
4                    1,68                          3                  0   
...                   ...                        ...                ...   
5315                    0                          0                  3   
5316                 1,84                         33                  0   
5317                    0                          0                  3   
5318                 2,21                         40                  0   
5319                    0                          0                  0   

     Media_Puntos_Visitantes  Puntos_Visitantes_Acumulados Resultados  \
0                          0                             0          x   
1                       0,47                             1          x   
2                          0                             0          1   
3                       0,79                             0          1   
4                          0                             0          1   
...                      ...                           ...        ...   
5315                    1,21                            23          2   
531

### Paso 2: Definimos  la matriz de entrenamiento y el conjunto de prueba

In [4]:
#Definimos las columnas del dataset que van a participar en la matriz
#Generamos la matriz
matriz =dataset_estadisticas_definitivo.drop(columns=['Resultados','Fecha','Equipo','Local/Visitante','Temporada','Media_Goles_Locales','Media_Goles_Visitantes','Media_Puntos_Locales','Media_Puntos_Visitantes'])


#Generamos el vector con el conjunto de datos que queremos predecir
vector = dataset_estadisticas_definitivo.Resultados.tolist()

### Paso 3: División de los datos en conjunto de entrenamiento y test

In [5]:
#Conjunto de entrenamiento
X_train = matriz
y_train = vector

X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size= 0.2,random_state = 123)

### Paso 4:  Definición Modelo

In [6]:
modelo = LogisticRegression(max_iter = 500)

### Paso 5:  Entrenamiento del Modelo

In [7]:
modelo.fit(X_train, y_train)

LogisticRegression(max_iter=500)

### Paso 6: Realizamos la predicción

In [8]:
predicciones = modelo.predict(X = X_test)
predicciones

array(['1', '1', '1', ..., '1', 'x', '1'], dtype='<U1')

### Paso 7: Evaluación modelo

#### Cálculo accuracy

In [9]:
scores = cross_val_score(modelo, matriz,vector)
print(f"El accuracy de test es: {100 * scores.mean()} %")

El accuracy de test es: 91.63533834586467 %


#### Cálculo Matriz de Confusión

In [10]:
from sklearn.metrics import confusion_matrix

matriz_confusion = confusion_matrix(y_test,predicciones)
print(matriz_confusion)

[[477   0  25]
 [  0 273  30]
 [ 37   4 218]]


#### Clasification Report

In [11]:
from sklearn.metrics import classification_report

reporte_clasificacion = classification_report(y_test, predicciones)

print(reporte_clasificacion)

              precision    recall  f1-score   support

           1       0.93      0.95      0.94       502
           2       0.99      0.90      0.94       303
           x       0.80      0.84      0.82       259

    accuracy                           0.91      1064
   macro avg       0.90      0.90      0.90      1064
weighted avg       0.91      0.91      0.91      1064

