In [1]:
#Importamos las  librerías necesarias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn import  metrics
from sklearn.metrics import accuracy_score

### Paso 1: Leemos el Dataset

In [2]:
dataset_estadisticas_definitivo = pd.read_csv(r"https://raw.githubusercontent.com/PabloLedo97/Datasets-Master-Big-Data/main/DatasetDefinitivo_Pablo_Ledo.csv",sep=";",encoding='latin-1');
dataset_estadisticas_definitivo

Equipo Local/Visitante  Goles_Locales  \
0          Málaga           Local              0   
1         Sevilla       Visitante              0   
2        Atlético           Local              1   
3      Las Palmas       Visitante              0   
4        Espanyol           Local              1   
...           ...             ...            ...   
5315   Villarreal       Visitante              0   
5316  R. Sociedad           Local              1   
5317     Atlético       Visitante              0   
5318      Sevilla           Local              1   
5319     Athletic       Visitante              0   

      Suma_Goles_Locales_Acumulados Media_Goles_Locales  Goles_Visitantes  \
0                                 0                1,37                 0   
1                                 0                   0                 0   
2                                 1                1,74                 0   
3                                 0                   0                 0   
4                                 1                1,16                 0   
...                             ...                 ...               ...   
5315                              0                   0                 2   
5316                             16                0,84                 0   
5317                              0                   0                 2   
5318                             36                1,89                 0   
5319                              0                   0                 0   

      Suma_Goles_Visitantes_Acumulados Media_Goles_Visitantes  Puntos_Locales  \
0                                    0                      0               1   
1                                    0                   0,68               0   
2                                    0                      0               3   
3                                    0                   1,05               0   
4                                    0                      0               3   
...                                ...                    ...             ...   
5315                                20                   1,21               0   
5316                                 0                      0               0   
5317                                32                   1,68               0   
5318                                 0                      0               3   
5319                                14                   0,74               0   

     Media_Puntos_Locales  Puntos_Locales_Acumulados  Puntos_Visitantes  \
0                    1,58                          1                  0   
1                       0                          0                  1   
2                    2,53                          3                  0   
3                       0                          0                  0   
4                    1,68                          3                  0   
...                   ...                        ...                ...   
5315                    0                          0                  3   
5316                 1,84                         33                  0   
5317                    0                          0                  3   
5318                 2,21                         40                  0   
5319                    0                          0                  0   

     Media_Puntos_Visitantes  Puntos_Visitantes_Acumulados Resultados  \
0                          0                             0          x   
1                       0,47                             1          x   
2                          0                             0          1   
3                       0,79                             0          1   
4                          0                             0          1   
...                      ...                           ...        ...   
5315                    1,21                            23          2   
531

### Paso 2: Definimos  la matriz de entrenamiento y el conjunto de prueba

In [3]:
#Definimos las columnas del dataset que van a participar en la matriz
goles_locales = dataset_estadisticas_definitivo.Goles_Locales.tolist()
goles_locales_acumulados = dataset_estadisticas_definitivo.Suma_Goles_Locales_Acumulados.tolist()
goles_visitantes = dataset_estadisticas_definitivo.Goles_Visitantes.tolist()
goles_visitantes_acumulados = dataset_estadisticas_definitivo.Suma_Goles_Visitantes_Acumulados.tolist()

#Generamos la matriz
matriz =np.array([goles_locales,goles_locales_acumulados,goles_visitantes,goles_visitantes_acumulados])


#Generamos el vector con el conjunto de datos que queremos predecir
vector = dataset_estadisticas_definitivo.Resultados.tolist()

### Paso 3: División de los datos en conjunto de entrenamiento y test

In [4]:
#Conjunto de entrenamiento
X_train = matriz.transpose()
y_train = vector

X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size= 0.2,random_state = 123)

### Paso 4:  Definición Modelo

In [5]:
modelo = CatBoostClassifier(iterations=1000,learning_rate=1,depth=2)

### Paso 5:  Entrenamiento del Modelo

In [6]:
modelo.fit(X_train, y_train)

0:	learn: 0.9510550	total: 156ms	remaining: 2m 36s
1:	learn: 0.8888077	total: 158ms	remaining: 1m 18s
2:	learn: 0.8439138	total: 159ms	remaining: 52.9s
3:	learn: 0.8247899	total: 160ms	remaining: 39.9s
4:	learn: 0.8182631	total: 162ms	remaining: 32.1s
5:	learn: 0.8156924	total: 163ms	remaining: 26.9s
6:	learn: 0.8148699	total: 164ms	remaining: 23.2s
7:	learn: 0.8141218	total: 165ms	remaining: 20.5s
8:	learn: 0.8112229	total: 166ms	remaining: 18.3s
9:	learn: 0.8072803	total: 167ms	remaining: 16.6s
10:	learn: 0.8058368	total: 168ms	remaining: 15.1s
11:	learn: 0.8053888	total: 170ms	remaining: 14s
12:	learn: 0.8032293	total: 171ms	remaining: 13s
13:	learn: 0.8027920	total: 172ms	remaining: 12.1s
14:	learn: 0.8018634	total: 173ms	remaining: 11.4s
15:	learn: 0.8010441	total: 174ms	remaining: 10.7s
16:	learn: 0.8005857	total: 176ms	remaining: 10.2s
17:	learn: 0.8004227	total: 177ms	remaining: 9.64s
18:	learn: 0.7999543	total: 178ms	remaining: 9.19s
19:	learn: 0.7986259	total: 179ms	remaining

298:	learn: 0.7675741	total: 507ms	remaining: 1.19s
299:	learn: 0.7675717	total: 508ms	remaining: 1.19s
300:	learn: 0.7675694	total: 510ms	remaining: 1.18s
301:	learn: 0.7675673	total: 511ms	remaining: 1.18s
302:	learn: 0.7675347	total: 512ms	remaining: 1.18s
303:	learn: 0.7674799	total: 513ms	remaining: 1.17s
304:	learn: 0.7674704	total: 514ms	remaining: 1.17s
305:	learn: 0.7674422	total: 515ms	remaining: 1.17s
306:	learn: 0.7674322	total: 517ms	remaining: 1.17s
307:	learn: 0.7674267	total: 518ms	remaining: 1.16s
308:	learn: 0.7674259	total: 519ms	remaining: 1.16s
309:	learn: 0.7673868	total: 520ms	remaining: 1.16s
310:	learn: 0.7673825	total: 521ms	remaining: 1.15s
311:	learn: 0.7673416	total: 522ms	remaining: 1.15s
312:	learn: 0.7673390	total: 524ms	remaining: 1.15s
313:	learn: 0.7672883	total: 525ms	remaining: 1.15s
314:	learn: 0.7672827	total: 526ms	remaining: 1.14s
315:	learn: 0.7672526	total: 527ms	remaining: 1.14s
316:	learn: 0.7671000	total: 528ms	remaining: 1.14s
317:	learn: 

628:	learn: 0.7616438	total: 855ms	remaining: 504ms
629:	learn: 0.7614054	total: 857ms	remaining: 503ms
630:	learn: 0.7613921	total: 858ms	remaining: 502ms
631:	learn: 0.7613894	total: 859ms	remaining: 500ms
632:	learn: 0.7613696	total: 860ms	remaining: 498ms
633:	learn: 0.7613599	total: 861ms	remaining: 497ms
634:	learn: 0.7613582	total: 862ms	remaining: 495ms
635:	learn: 0.7612853	total: 863ms	remaining: 494ms
636:	learn: 0.7612845	total: 864ms	remaining: 492ms
637:	learn: 0.7611853	total: 865ms	remaining: 491ms
638:	learn: 0.7611847	total: 866ms	remaining: 489ms
639:	learn: 0.7611319	total: 867ms	remaining: 488ms
640:	learn: 0.7611314	total: 868ms	remaining: 486ms
641:	learn: 0.7611307	total: 869ms	remaining: 485ms
642:	learn: 0.7611234	total: 871ms	remaining: 483ms
643:	learn: 0.7611056	total: 871ms	remaining: 482ms
644:	learn: 0.7610474	total: 872ms	remaining: 480ms
645:	learn: 0.7610322	total: 873ms	remaining: 479ms
646:	learn: 0.7610231	total: 874ms	remaining: 477ms
647:	learn: 

801:	learn: 0.7590121	total: 1.03s	remaining: 254ms
802:	learn: 0.7590099	total: 1.03s	remaining: 252ms
803:	learn: 0.7589676	total: 1.03s	remaining: 251ms
804:	learn: 0.7589673	total: 1.03s	remaining: 250ms
805:	learn: 0.7589667	total: 1.03s	remaining: 248ms
806:	learn: 0.7589636	total: 1.03s	remaining: 247ms
807:	learn: 0.7589633	total: 1.03s	remaining: 246ms
808:	learn: 0.7589469	total: 1.03s	remaining: 244ms
809:	learn: 0.7589382	total: 1.04s	remaining: 243ms
810:	learn: 0.7589271	total: 1.04s	remaining: 242ms
811:	learn: 0.7589178	total: 1.04s	remaining: 240ms
812:	learn: 0.7588986	total: 1.04s	remaining: 239ms
813:	learn: 0.7588979	total: 1.04s	remaining: 238ms
814:	learn: 0.7588949	total: 1.04s	remaining: 236ms
815:	learn: 0.7588885	total: 1.04s	remaining: 235ms
816:	learn: 0.7588854	total: 1.04s	remaining: 234ms
817:	learn: 0.7588849	total: 1.04s	remaining: 232ms
818:	learn: 0.7588846	total: 1.04s	remaining: 231ms
819:	learn: 0.7588690	total: 1.05s	remaining: 230ms
820:	learn: 

977:	learn: 0.7574167	total: 1.2s	remaining: 27ms
978:	learn: 0.7574118	total: 1.2s	remaining: 25.8ms
979:	learn: 0.7573996	total: 1.2s	remaining: 24.6ms
980:	learn: 0.7573991	total: 1.21s	remaining: 23.3ms
981:	learn: 0.7573978	total: 1.21s	remaining: 22.1ms
982:	learn: 0.7573784	total: 1.21s	remaining: 20.9ms
983:	learn: 0.7573174	total: 1.21s	remaining: 19.6ms
984:	learn: 0.7573143	total: 1.21s	remaining: 18.4ms
985:	learn: 0.7573040	total: 1.21s	remaining: 17.2ms
986:	learn: 0.7573039	total: 1.21s	remaining: 16ms
987:	learn: 0.7572990	total: 1.21s	remaining: 14.7ms
988:	learn: 0.7572886	total: 1.21s	remaining: 13.5ms
989:	learn: 0.7572851	total: 1.21s	remaining: 12.3ms
990:	learn: 0.7572845	total: 1.22s	remaining: 11ms
991:	learn: 0.7572833	total: 1.22s	remaining: 9.81ms
992:	learn: 0.7572828	total: 1.22s	remaining: 8.58ms
993:	learn: 0.7572748	total: 1.22s	remaining: 7.35ms
994:	learn: 0.7572742	total: 1.22s	remaining: 6.13ms
995:	learn: 0.7572738	total: 1.22s	remaining: 4.9ms
996

### Paso 6: Realizamos la predicción

In [7]:
predicciones = modelo.predict(X_test)
predicciones

array([['x'],
       ['1'],
       ['2'],
       ...,
       ['1'],
       ['1'],
       ['1']], dtype=object)

### Paso 7: Evaluación modelo

#### Cálculo accuracy

In [8]:
accuracy = accuracy_score(y_true= y_test,y_pred= predicciones,normalize = True)
print(f"El accuracy de test es: {100 * accuracy} %")

El accuracy de test es: 60.43233082706767 %


#### Cálculo Matriz de Confusión

In [11]:
from sklearn.metrics import confusion_matrix

matriz_confusion = confusion_matrix(y_test,predicciones)
print(matriz_confusion)

[[379  39  84]
 [ 48 203  52]
 [110  88  61]]


#### Clasification Report

In [17]:
from sklearn.metrics import classification_report

reporte_clasificacion = classification_report(y_test, predicciones)

print(reporte_clasificacion)

              precision    recall  f1-score   support

           1       0.71      0.75      0.73       502
           2       0.62      0.67      0.64       303
           x       0.31      0.24      0.27       259

    accuracy                           0.60      1064
   macro avg       0.54      0.55      0.55      1064
weighted avg       0.58      0.60      0.59      1064

