In [8]:
#Importamos las librerías necesarias
import pandas as pd
import numpy as np
from sklearn.neighbors  import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

### Paso 1: Leemos el Dataset

In [9]:
dataset_estadisticas_definitivo = pd.read_csv(r"https://raw.githubusercontent.com/PabloLedo97/Datasets-Master-Big-Data/main/DatasetDefinitivo_Pablo_Ledo.csv",sep=";",encoding='latin-1');
dataset_estadisticas_definitivo

Equipo Local/Visitante  Goles_Locales  \
0          Málaga           Local              0   
1         Sevilla       Visitante              0   
2        Atlético           Local              1   
3      Las Palmas       Visitante              0   
4        Espanyol           Local              1   
...           ...             ...            ...   
5315   Villarreal       Visitante              0   
5316  R. Sociedad           Local              1   
5317     Atlético       Visitante              0   
5318      Sevilla           Local              1   
5319     Athletic       Visitante              0   

      Suma_Goles_Locales_Acumulados  Goles_Visitantes  \
0                                 0                 0   
1                                 0                 0   
2                                 1                 0   
3                                 0                 0   
4                                 1                 0   
...                             ...               ...   
5315                              0                 2   
5316                             16                 0   
5317                              0                 2   
5318                             36                 0   
5319                              0                 0   

      Suma_Goles_Visitantes_Acumulados Resultados       Fecha  Temporada  
0                                    0          x  21/08/2015  2015/2016  
1                                    0          x  21/08/2015  2015/2016  
2                                    0          1  22/08/2015  2015/2016  
3                                    0          1  22/08/2015  2015/2016  
4                                    0          1  22/08/2015  2015/2016  
...                                ...        ...         ...        ...  
5315                                20          2  22/05/2022  2021/2022  
5316                                 0          2  22/05/2022  2021/2022  
5317                                32          2  22/05/2022  2021/2022  
5318                                 0          1  22/05/2022  2021/2022  
5319                                14          1  22/05/2022  2021/2022  

[5320 rows x 9 columns]

### Paso 2: Definimos  la matriz de entrenamiento y el conjunto de prueba

In [10]:
#Definimos las columnas del dataset que van a participar en la matriz
goles_locales = dataset_estadisticas_definitivo.Goles_Locales.tolist()
goles_locales_acumulados = dataset_estadisticas_definitivo.Suma_Goles_Locales_Acumulados.tolist()
goles_visitantes = dataset_estadisticas_definitivo.Goles_Visitantes.tolist()
goles_visitantes_acumulados = dataset_estadisticas_definitivo.Suma_Goles_Visitantes_Acumulados.tolist()

#Generamos la matriz
matriz =np.array([goles_locales,goles_locales_acumulados,goles_visitantes,goles_visitantes_acumulados])


#Generamos el vector con el conjunto de datos que queremos predecir
vector = dataset_estadisticas_definitivo.Resultados.tolist()

### Paso 3: División de los datos en conjunto de entrenamiento y test

In [12]:
#Conjunto de entrenamiento
X = matriz.transpose()
Y = vector
X, X_test,Y, y_test = train_test_split(X,Y,test_size= 0.1,random_state = 123)

### Paso 4:  Definición Modelo

In [13]:
knn = KNeighborsClassifier(n_neighbors=5)

### Paso 5:  Entrenamiento del Modelo

In [14]:
knn.fit(X, Y)

KNeighborsClassifier()

### Paso 6: Realizamos la predicción

In [15]:
predicciones = knn.predict(X_test)
predicciones

array(['x', '1', '2', '1', '1', '1', '1', 'x', 'x', '1', '1', '2', '1',
       'x', '1', '2', '1', '1', 'x', '1', '2', '1', 'x', '1', '2', 'x',
       '1', '1', '1', '2', '2', '1', '2', '1', '2', '1', '1', '1', '2',
       '1', '2', '2', '1', '1', '1', 'x', '2', '2', '1', '2', '2', '1',
       '1', '1', 'x', '1', '1', 'x', '1', '2', '1', '1', '2', 'x', '2',
       '1', 'x', 'x', '1', '1', '1', 'x', '2', '1', '1', '2', '2', '2',
       '1', '2', 'x', '2', '2', '2', 'x', 'x', '2', '1', '1', 'x', '1',
       '1', 'x', '1', '2', '1', '1', '1', '1', '1', '1', '1', 'x', '1',
       'x', '1', 'x', '1', '2', '1', 'x', 'x', '1', '2', '2', '2', 'x',
       '2', '2', '1', '2', '2', '1', '2', '1', '1', '2', '1', '2', '1',
       '1', '1', '1', '2', '2', '1', '1', '1', '2', '1', 'x', '1', '2',
       'x', '1', '2', '1', '2', '1', '1', '1', 'x', '2', '2', '1', '1',
       '1', '1', '2', '2', '1', '1', '1', '1', '1', '1', '1', '1', 'x',
       '1', '1', 'x', '1', '1', '1', '1', '2', '1', '2', '2', 'x

### Paso 7: Evaluación modelo

#### Cálculo accuracy

In [16]:
accuracy = accuracy_score(y_true= y_test,y_pred= predicciones,normalize = True)
print(f"El accuracy de test es: {100 * accuracy} %")

El accuracy de test es: 56.766917293233085 %


#### Cálculo Matriz de Confusión

In [18]:
from sklearn.metrics import confusion_matrix

matriz_confusion = confusion_matrix(y_test,predicciones)
print(matriz_confusion)

[[190  28  35]
 [ 25  89  39]
 [ 62  41  23]]


#### Clasification Report

In [19]:
from sklearn.metrics import classification_report

reporte_clasificacion = classification_report(y_test, predicciones)

print(reporte_clasificacion)

              precision    recall  f1-score   support

           1       0.69      0.75      0.72       253
           2       0.56      0.58      0.57       153
           x       0.24      0.18      0.21       126

    accuracy                           0.57       532
   macro avg       0.50      0.51      0.50       532
weighted avg       0.54      0.57      0.55       532

