In [1]:
#Importamos las  librerías necesarias
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn import  metrics
from sklearn.metrics import accuracy_score

### Paso 1: Leemos el Dataset

In [2]:
dataset_estadisticas_definitivo = pd.read_csv(r"https://raw.githubusercontent.com/PabloLedo97/Datasets-Master-Big-Data/main/DatasetDefinitivo_Pablo_Ledo.csv",sep=";",encoding='latin-1');
dataset_estadisticas_definitivo

Equipo Local/Visitante  Goles_Locales  \
0          Málaga           Local              0   
1         Sevilla       Visitante              0   
2        Atlético           Local              1   
3      Las Palmas       Visitante              0   
4        Espanyol           Local              1   
...           ...             ...            ...   
5315   Villarreal       Visitante              0   
5316  R. Sociedad           Local              1   
5317     Atlético       Visitante              0   
5318      Sevilla           Local              1   
5319     Athletic       Visitante              0   

      Suma_Goles_Locales_Acumulados Media_Goles_Locales  Goles_Visitantes  \
0                                 0                1,37                 0   
1                                 0                   0                 0   
2                                 1                1,74                 0   
3                                 0                   0                 0   
4                                 1                1,16                 0   
...                             ...                 ...               ...   
5315                              0                   0                 2   
5316                             16                0,84                 0   
5317                              0                   0                 2   
5318                             36                1,89                 0   
5319                              0                   0                 0   

      Suma_Goles_Visitantes_Acumulados Media_Goles_Visitantes  Puntos_Locales  \
0                                    0                      0               1   
1                                    0                   0,68               0   
2                                    0                      0               3   
3                                    0                   1,05               0   
4                                    0                      0               3   
...                                ...                    ...             ...   
5315                                20                   1,21               0   
5316                                 0                      0               0   
5317                                32                   1,68               0   
5318                                 0                      0               3   
5319                                14                   0,74               0   

     Media_Puntos_Locales  Puntos_Locales_Acumulados  Puntos_Visitantes  \
0                    1,58                          1                  0   
1                       0                          0                  1   
2                    2,53                          3                  0   
3                       0                          0                  0   
4                    1,68                          3                  0   
...                   ...                        ...                ...   
5315                    0                          0                  3   
5316                 1,84                         33                  0   
5317                    0                          0                  3   
5318                 2,21                         40                  0   
5319                    0                          0                  0   

     Media_Puntos_Visitantes  Puntos_Visitantes_Acumulados Resultados  \
0                          0                             0          x   
1                       0,47                             1          x   
2                          0                             0          1   
3                       0,79                             0          1   
4                          0                             0          1   
...                      ...                           ...        ...   
5315                    1,21                            23          2   
531

### Paso 2: Definimos  la matriz de entrenamiento y el conjunto de prueba

In [3]:
#Definimos las columnas del dataset que van a participar en la matriz
#Generamos la matriz
matriz =dataset_estadisticas_definitivo.drop(columns=['Resultados','Fecha','Equipo','Local/Visitante','Temporada','Media_Goles_Locales','Media_Goles_Visitantes','Media_Puntos_Locales','Media_Puntos_Visitantes'])


#Generamos el vector con el conjunto de datos que queremos predecir
vector = dataset_estadisticas_definitivo.Resultados.tolist()

### Paso 3: División de los datos en conjunto de entrenamiento y test

In [5]:
#Conjunto de entrenamiento
X_train = matriz
y_train = vector

X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size= 0.2,random_state = 123)

### Paso 4:  Definición Modelo

In [6]:
modelo = CatBoostClassifier(iterations=1000,learning_rate=1,depth=2)

### Paso 5:  Entrenamiento del Modelo

In [7]:
modelo.fit(X_train, y_train)

0:	learn: 0.7098990	total: 168ms	remaining: 2m 48s
1:	learn: 0.4040191	total: 170ms	remaining: 1m 24s
2:	learn: 0.2098573	total: 172ms	remaining: 57s
3:	learn: 0.1488666	total: 173ms	remaining: 43s
4:	learn: 0.0800449	total: 174ms	remaining: 34.6s
5:	learn: 0.0652500	total: 175ms	remaining: 29s
6:	learn: 0.0482364	total: 176ms	remaining: 25s
7:	learn: 0.0395904	total: 177ms	remaining: 22s
8:	learn: 0.0322949	total: 179ms	remaining: 19.7s
9:	learn: 0.0309736	total: 180ms	remaining: 17.9s
10:	learn: 0.0260018	total: 182ms	remaining: 16.3s
11:	learn: 0.0218555	total: 183ms	remaining: 15.1s
12:	learn: 0.0192611	total: 184ms	remaining: 14s
13:	learn: 0.0173970	total: 185ms	remaining: 13s
14:	learn: 0.0167704	total: 186ms	remaining: 12.2s
15:	learn: 0.0153448	total: 188ms	remaining: 11.5s
16:	learn: 0.0145083	total: 189ms	remaining: 10.9s
17:	learn: 0.0138196	total: 190ms	remaining: 10.4s
18:	learn: 0.0133026	total: 192ms	remaining: 9.89s
19:	learn: 0.0131511	total: 193ms	remaining: 9.45s
20

254:	learn: 0.0101095	total: 514ms	remaining: 1.5s
255:	learn: 0.0101093	total: 515ms	remaining: 1.5s
256:	learn: 0.0101093	total: 517ms	remaining: 1.49s
257:	learn: 0.0101093	total: 518ms	remaining: 1.49s
258:	learn: 0.0101091	total: 520ms	remaining: 1.49s
259:	learn: 0.0101091	total: 521ms	remaining: 1.48s
260:	learn: 0.0101090	total: 523ms	remaining: 1.48s
261:	learn: 0.0101089	total: 524ms	remaining: 1.48s
262:	learn: 0.0101089	total: 526ms	remaining: 1.47s
263:	learn: 0.0101089	total: 527ms	remaining: 1.47s
264:	learn: 0.0101088	total: 528ms	remaining: 1.47s
265:	learn: 0.0101088	total: 530ms	remaining: 1.46s
266:	learn: 0.0101079	total: 531ms	remaining: 1.46s
267:	learn: 0.0101051	total: 532ms	remaining: 1.45s
268:	learn: 0.0101050	total: 534ms	remaining: 1.45s
269:	learn: 0.0101050	total: 535ms	remaining: 1.45s
270:	learn: 0.0101049	total: 536ms	remaining: 1.44s
271:	learn: 0.0101049	total: 538ms	remaining: 1.44s
272:	learn: 0.0101022	total: 539ms	remaining: 1.44s
273:	learn: 0.

516:	learn: 0.0100083	total: 859ms	remaining: 802ms
517:	learn: 0.0100083	total: 861ms	remaining: 801ms
518:	learn: 0.0100083	total: 863ms	remaining: 800ms
519:	learn: 0.0100083	total: 864ms	remaining: 798ms
520:	learn: 0.0100082	total: 866ms	remaining: 796ms
521:	learn: 0.0100082	total: 867ms	remaining: 794ms
522:	learn: 0.0100082	total: 868ms	remaining: 792ms
523:	learn: 0.0100082	total: 870ms	remaining: 790ms
524:	learn: 0.0100082	total: 871ms	remaining: 788ms
525:	learn: 0.0100082	total: 873ms	remaining: 786ms
526:	learn: 0.0100081	total: 874ms	remaining: 784ms
527:	learn: 0.0100081	total: 876ms	remaining: 783ms
528:	learn: 0.0100081	total: 877ms	remaining: 781ms
529:	learn: 0.0100081	total: 879ms	remaining: 779ms
530:	learn: 0.0100081	total: 880ms	remaining: 778ms
531:	learn: 0.0100067	total: 882ms	remaining: 776ms
532:	learn: 0.0100067	total: 883ms	remaining: 774ms
533:	learn: 0.0100067	total: 884ms	remaining: 772ms
534:	learn: 0.0100065	total: 886ms	remaining: 770ms
535:	learn: 

724:	learn: 0.0099869	total: 1.2s	remaining: 455ms
725:	learn: 0.0099866	total: 1.2s	remaining: 453ms
726:	learn: 0.0099866	total: 1.2s	remaining: 452ms
727:	learn: 0.0099848	total: 1.2s	remaining: 450ms
728:	learn: 0.0099846	total: 1.21s	remaining: 448ms
729:	learn: 0.0099846	total: 1.21s	remaining: 446ms
730:	learn: 0.0099846	total: 1.21s	remaining: 445ms
731:	learn: 0.0099846	total: 1.21s	remaining: 443ms
732:	learn: 0.0099846	total: 1.21s	remaining: 441ms
733:	learn: 0.0099845	total: 1.21s	remaining: 440ms
734:	learn: 0.0099845	total: 1.21s	remaining: 438ms
735:	learn: 0.0099845	total: 1.22s	remaining: 436ms
736:	learn: 0.0099843	total: 1.22s	remaining: 434ms
737:	learn: 0.0099843	total: 1.22s	remaining: 433ms
738:	learn: 0.0099834	total: 1.22s	remaining: 431ms
739:	learn: 0.0099834	total: 1.22s	remaining: 429ms
740:	learn: 0.0099834	total: 1.22s	remaining: 427ms
741:	learn: 0.0099834	total: 1.22s	remaining: 426ms
742:	learn: 0.0099834	total: 1.22s	remaining: 424ms
743:	learn: 0.00

989:	learn: 0.0099656	total: 1.55s	remaining: 15.6ms
990:	learn: 0.0099654	total: 1.55s	remaining: 14.1ms
991:	learn: 0.0099654	total: 1.55s	remaining: 12.5ms
992:	learn: 0.0099654	total: 1.55s	remaining: 10.9ms
993:	learn: 0.0099654	total: 1.55s	remaining: 9.37ms
994:	learn: 0.0099654	total: 1.55s	remaining: 7.81ms
995:	learn: 0.0099654	total: 1.55s	remaining: 6.25ms
996:	learn: 0.0099654	total: 1.56s	remaining: 4.68ms
997:	learn: 0.0099654	total: 1.56s	remaining: 3.12ms
998:	learn: 0.0099654	total: 1.56s	remaining: 1.56ms
999:	learn: 0.0099654	total: 1.56s	remaining: 0us


### Paso 6: Realizamos la predicción

In [8]:
predicciones = modelo.predict(X_test)
predicciones

array([['1'],
       ['1'],
       ['x'],
       ...,
       ['1'],
       ['x'],
       ['1']], dtype=object)

### Paso 7: Evaluación modelo

#### Cálculo accuracy

In [9]:
accuracy = accuracy_score(y_true= y_test,y_pred= predicciones,normalize = True)
print(f"El accuracy de test es: {100 * accuracy} %")

El accuracy de test es: 99.62406015037594 %


#### Cálculo Matriz de Confusión

In [10]:
from sklearn.metrics import confusion_matrix

matriz_confusion = confusion_matrix(y_test,predicciones)
print(matriz_confusion)

[[502   0   0]
 [  4 299   0]
 [  0   0 259]]


#### Clasification Report

In [11]:
from sklearn.metrics import classification_report

reporte_clasificacion = classification_report(y_test, predicciones)

print(reporte_clasificacion)

              precision    recall  f1-score   support

           1       0.99      1.00      1.00       502
           2       1.00      0.99      0.99       303
           x       1.00      1.00      1.00       259

    accuracy                           1.00      1064
   macro avg       1.00      1.00      1.00      1064
weighted avg       1.00      1.00      1.00      1064

